
server:
  port: 9006

spring:
  application:
  name: cloud-config-server
  cloud:
    config:
      # config远程分支
      label: master
      # git远程信息配置
      server:
        git:
          # 该路径不能用作远程git'配置文件地址，这不是一个独立的git仓库项目地址
          # uri: https://github.com/coderwing/coderwing-cloud/tree/master/cloud-config/config-files/
          uri: https://github.com/forezp/SpringcloudConfig/
          searchPaths: respo
          # 公开仓库不需要使用用户名和密码
          username:
          password:
