
server:
  port: 9006

spring:
  application:
  name: cloud-config-server
  cloud:
    config:
      # config远程分支
      label: master
      # git远程信息配置
      server:
        git:
          uri: https://github.com/coderwing/coderwing-cloud/tree/master/cloud-config/config-files/
          searchPaths: respo
          # 公开仓库不需要使用用户名和密码
          username:
          password:
