
server:
  port: 9004

spring:
  application:
    name: consume-feign

## Eureka 注册 client配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

## 打开Feign的断路器支持
feign:
  hystrix:
    enabled: true