
server:
  port: 8761

spring:
  application:
    name: eureka-server

## eureka 也是一个服务client，也需要配置对应的client信息
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      # 直接访问：http:localhost:8761
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/