
server:
  port: 9010

spring:
  application:
    name: net-gateway
  # 这里用做限流算法使用
  redis:
    host: localhost
    port: 6379
    database: 0

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      # 这是一个集合属性，对应的每一项开头都要使用 -
      default-filters:
        - AddResponseHeader=X-Response-Default-Foo, Default-Bar
      routes:
        -
          id: BIZ-USER-API-1
          # lb代表从注册中心获取服务
          uri: lb://BIZ-USER-API
          # 策略有很多种
          # 参考：https://cloud.spring.io/spring-cloud-static/spring-cloud-gateway/2.2.1.RELEASE/reference/html/#gateway-request-predicates-factories
          predicates:
            # 转发该路径
            # 等于访问http://BIZ-USER-API/user/**
            # - Path=/user/**

            # 使用前缀
            - Path=/userapi/**
          # 带前缀
          filters:
            # 表示在转发时去掉userapi
            - StripPrefix=1
            -
            # 限流过滤器
            - name: RequestRateLimiter
                args:
                  # 限流解析器bean名称，使用SpEl表达式从Spring容器中获取bean对象，实现了KeyResolver接口，实现resolve方法
                  key-resolver: '#{@hostAddrKeyResolver}'
                  # 令牌桶美妙填充速率
                  redis-rate-limiter.replenishRate: 10
                  # 令牌桶容量
                  redis-rate-limiter.burstCapacity: 100

        ## 第二个路由配置
        -
          id: BIZ-USER-API-2
          # lb代表从注册中心获取服务
          uri: lb://BIZ-USER-API
          predicates:
            # 转发该路径
            # 等于访问http://BIZ-USER-API/user/**
            # - Path=/user/**

            # 使用前缀
            - Path=/userapi2/**
          # 带前缀
          filters:
            # 表示在转发时去掉userapi
            - StripPrefix=1
            # 使用Hystrix，注意：断路器是放在filter中的
            - name: Hystrix
              args:
                name: myfallbackcmd
                # 断路转发的uri
                fallbackUri: forward:/user/fallback



## Eureka 注册 client配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

